#!/usr/bin/ruby
require_relative 'expression'
ARGV.empty? and p"NO AARGV" and exit
open("../players/init#{ARGV[2]}.rb","wb")<<open("../players/init#{ARGV[0]}.rb","rb").read
open("../players/init#{ARGV[3]}.rb","wb")<<open("../players/init#{ARGV[1]}.rb","rb").read

