#!/usr/bin/ruby
require_relative "expression"
def init(node,depth)
  table={
    :+ => 2,
    :~ => 1,
    :* => 2
  }
  depth==0 and return rand(10)
  op=table.keys.shuffle.first
  node<<op
  table[op].times{
    node<<init([],depth-1)
  }
  return node
end
#init(tree=[],3)
S.init(tree=S.new(:R),3)
p tree
p Marshal.load(Marshal.dump(tree))